
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a T4 template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace YourNamespace
{
    /// <summary>
    /// Represents a Data Transfer Object for Account Receivable Debtor Invoice Data..
    /// </summary>
    public class AccountReceivableDebtorInvoiceData
    {
        /// <summary>
        /// Id
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Invoice Header Id
        /// </summary>
        public int InvoiceHeaderId { get; set; }

        /// <summary>
        /// Line Number
        /// </summary>
        public int LineNumber { get; set; }

        /// <summary>
        /// Description
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// Rate Code
        /// </summary>
        public int RateCode { get; set; }

        /// <summary>
        /// Amount
        /// </summary>
        public decimal Amount { get; set; }

        /// <summary>
        /// Quality
        /// </summary>
        public decimal Quality { get; set; }

        /// <summary>
        /// Gst Code
        /// </summary>
        public short GstCode { get; set; }

        /// <summary>
        /// Gst Amount
        /// </summary>
        public decimal GstAmount { get; set; }

        /// <summary>
        /// Ledger Account
        /// </summary>
        public string LedgerAccount { get; set; }

        /// <summary>
        /// Destination Invoice Header Id
        /// </summary>
        public int DestinationInvoiceHeaderId { get; set; }

        /// <summary>
        /// Destination Invoice Liner Id
        /// </summary>
        public int DestinationInvoiceLinerId { get; set; }

        /// <summary>
        /// Row Version
        /// </summary>
        public long RowVersion { get; set; }

        /// <summary>
        /// Created Date Time
        /// </summary>
        public DateTimeOffSet CreatedDateTime { get; set; }

        /// <summary>
        /// Modified Date Time
        /// </summary>
        public DateTimeOffSet ModifiedDateTime { get; set; }

        /// <summary>
        /// Modified Operator Id
        /// </summary>
        public int ModifiedOperatorId { get; set; }

    }
}
