

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a T4 template.
// </auto-generated>
//------------------------------------------------------------------------------
using FluentValidation;

namespace YourNamespace.Validators
{
    public class ProductValidator : AbstractValidator<Product>
    {
        public ProductValidator()
        {
            RuleFor(x => x.Name)
                .NotEmpty().WithMessage("Name is required.");
            RuleFor(x => x.Price)
                .GreaterThan(0).WithMessage("Price must be greater than zero.");
            RuleFor(x => x.StockQuantity)
                .GreaterThanOrEqualTo(0).WithMessage("Stock quantity cannot be negative.");
            RuleFor(x => x.ReleaseDate)
                .LessThanOrEqualTo(DateTime.Now).WithMessage("Release date cannot be in the future.");
        }
    }
}
